### PR TITLE
Fixed error on compiling the gem in 64 bit windows

### PR DESCRIPTION
**Pull request by ghost**
Modified CFLAGS to compile under 64 bit windows using DevKit 4.7.2 64 bit

### CODE REVIEW

**Comment by headius** [comment]
Thanks! I'll push 1.1.7 and you can confirm it's working properly now.

**Comment by headius** [comment]
1.1.7 has been pushed to rubygems.org. (/cc #13)

**Comment by johnnyshields** [comment]
I'm still getting an error on Windows x64, mingw32, and Ruby 1.9.3

Upgrading to Ruby 2.0 mingw64 fixed the problem 

```
Installing atomic (1.1.7) 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        C:/ruby/bin/ruby.exe extconf.rb 
creating Makefile

make
generating atomic_reference-i386-mingw32.def
compiling atomic_reference.c
atomic_reference.c: In function 'ir_compare_and_set':
atomic_reference.c:58:2: error: #error No CAS operation available for this platform
make: *** [atomic_reference.o] Error 1


Gem files will remain installed in C:/ruby/lib/ruby/gems/1.9.1/gems/atomic-1.1.7 for inspection.
Results logged to C:/ruby/lib/ruby/gems/1.9.1/gems/atomic-1.1.7/ext/gem_make.out
An error occurred while installing atomic (1.1.7), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.7'` succeeds before bundling.
```

**Comment by ghost** [comment]
Yup, I was on Ruby 2.0.

**Comment by headius** [comment]
Ahh hmm...so there's still something not quite right for the 1.9.3 build. Can someone with Windows help figure out a test that works there too?

**Comment by ftomassetti** [comment]
I get the same error trying to install version 1.1.10 on my server on webfaction

**Comment by ftomassetti** [comment]
I am running ruby 2.0.0p195 (2013-05-14 revision 40734) [i386-linux], gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)

**Comment by sintro** [comment]
I have Windows 7 x64, trying to instal atomic on both rubyinstaller-2.0.0-p247 and rubyinstaller-2.0.0-p247-x64, and getting error on both. Here is 64`s one:

D:\Ruby200-x64\bin>gem.bat install atomic
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing atomic:
        ERROR: Failed to build gem native extension.

```
D:/Ruby200-x64/bin/ruby.exe extconf.rb
```

creating Makefile

make "DESTDIR="
generating atomic_reference-x64-mingw32.def
compiling atomic_reference.c
atomic_reference.c: In function 'ir_compare_and_set':
atomic_reference.c:58:2: error: #error No CAS operation available for this platf
orm
make: **\* [atomic_reference.o] Error 1

Gem files will remain installed in D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/atomi
c-1.1.10 for inspection.
Results logged to D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/atomic-1.1.10/ext/gem_
make.out

**Comment by acollard** [comment]
Same issue as sintro.  Trying to install atomic 1.1.14.  1.1.10 doesn't work either.

Running with the following:
Windows 7 x64
rubyinstaller-2.0.0-p247-x64
DevKit-mingw64-64-4.7.2-20130224-1432-sfx

Any help would be very much appreciated.

**Pull request merged**
