### PR TITLE
Parallel benchmark added

### PR DESCRIPTION
**Pull request by zimbatm**
it may need a little bit of tweaking but the base is there

what is missing st that I didn't find a way to _not_ collect the threads during the benchmark

by the way the numbers show that it's pretty fast in comparison with mutexes:

```
ruby test/bench_atomic.rb 100
*** Sequencial updates ***
                user     system      total        real
no lock     0.020000   0.000000   0.020000 (  0.013727)
mutex       0.060000   0.000000   0.060000 (  0.064501)
atomic      0.070000   0.010000   0.080000 (  0.074339)
*** Parallel updates ***
                user     system      total        real
no lock     0.020000   0.010000   0.030000 (  0.024614)
mutex       0.490000   0.880000   1.370000 (  1.165315)
atomic      0.080000   0.000000   0.080000 (  0.085178)
```

### CODE REVIEW

**Comment by headius** [comment]
Thanks...I'll see if I can get it to run without measuring any thread-wrangling overhead.

**Comment by zimbatm** [comment]
Actually, wouldn't it be enough to stop the GC during the runs ?

**Comment by headius** [comment]
That might work fine for MRI, but it's not possible to disable the JVM GC from userland code.

**Comment by headius** [comment]
Poking around for GC disabling yielded a number of posts that simply suggested bumping up the heap size to avoid a GC run.

In other news, I realized there's a small "buglet" with the benchmark. On my system, with four cores, the atomic update frequently fails to update the value because another thread has very often updated the reference in the meantime. This means that the atomic numbers are considerably _worse_ than synchronized, because they have to re-run the block fairly often.

The synchronized case is faster when you have many threads contending solely because the overhead of re-running blocks for atomic update outweighs any locking cost.

So this may not be a good example case when running on multiple cores. You can see the effect if you pass -d to JRuby...a bunch of these will show up:

```
Exception `Atomic::ConcurrentUpdateError' at /Users/headius/projects/ruby-atomic/lib/atomic.rb:39 - Update failed
Exception `Atomic::ConcurrentUpdateError' at /Users/headius/projects/ruby-atomic/lib/atomic.rb:39 - Update failed
Exception `Atomic::ConcurrentUpdateError' at /Users/headius/projects/ruby-atomic/lib/atomic.rb:39 - Update failed
Exception `Atomic::ConcurrentUpdateError' at /Users/headius/projects/ruby-atomic/lib/atomic.rb:39 - Update failed
```

I'll have to ponder a better benchmark this afternoon.

**Comment by zimbatm** [comment]
Interesting. Aren't exceptions also a bit expensive for doing control-flow ?

Providing specialized operators like incr / decr (cf. redis) would maybe be interesting performance-wise since the execution could be kept at low-level instead of calling a block. I understand that it would increase the API surface so it's less desirable in that regard.

By writing the benchmark I also noticed that it's not easy to know or select which engine the runtime is going to use. Just wanted to share this as well.

**Comment by headius** [comment]
Yes, exceptions are definitely expensive. I believe the main problem with the current logic is that if a CAS fails, we raise an exception, rather than reporting to the caller that it simply failed. Partially an API design problem. I'll see what I can do to improve it.

**Comment by headius** [comment]
Ok, I made a few modifications in 66b2310 to provide fastest-path for compare-and-set and forced-update compare-and-set, and also modified try_update to have a bogus backtrace (since it's almost certainly a control-flow exception) unless $VERBOSE is set. The new numbers put mutex and atomic closer together, but atomic still doesn't win because it still has to re-run the block a lot. Hard to measure atomic-with-retry against atomic-because-synchronous, I guess.

Also some tweaks to the benchmark, which has moved under examples. Pushed 0.0.6 gem just now.

**Pull request merged**
