### PR TITLE
Just added some benchmarks

### PR DESCRIPTION
**Pull request by zimbatm**
I was just wondering how costly it was in comparison with mutexes in sequencial access.

my numbers on mri 1.9.2 for 100k increments of 1:

```
                user     system      total        real
simple      0.020000   0.000000   0.020000 (  0.013406)
mutex       0.060000   0.000000   0.060000 (  0.066982)
atomic      0.180000   0.000000   0.180000 (  0.187191)
```

The overhead does not look really significant but there is no performance advantage over mutexes on sequencial access.

I know. This was the easy part. Next I need to test the same operation but in parallel over a varying number of threads.

Some other ideas:
- propose common atomic operations like incr/decr (like redis)
- freeze mutable objects to avoid bad surprises

### CODE REVIEW

**Comment by headius** [comment]
I would't expect a ton of perf difference for a single-threaded case, but for a multi-threaded case it may make a larger difference.

Of course the code that's consuming the atomic objects may overshadow any perf gains too.

**Comment by zimbatm** [comment]
Any ideas how I could reliably test concurrent modification speed ? I was thinking something in the line of: start N*2 paused threads, with even ones incrementing and odd ones decrementing a value. Then start all of them at the same time

**Comment by headius** [comment]
Yeah, that's what I'd do. You may actually want to snapshot running threads...like wait to start timing until you know all threads are running, time them for a certain number of modifications (or fixed time and measure how many mods they can make) and then stop timing before terminating the threads. That would avoid measuring any thread synchronization used solely to manage the threads.

**Comment by zimbatm** [comment]
Thanks, new pull request :)

**Pull request merged**
